// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utynvssdbjeiujjvsrmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0eW52c3NkYmplaXVqanZzcm1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwMzM0NjAsImV4cCI6MjA3NTYwOTQ2MH0.1UdchHU1Bn9GLwJEL6A7yDwVq2HyQy47dzbxhmi-LV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});